/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData done_all = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData clipboard = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData th_large_outline = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData loop_outline = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData box = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData signal = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData th = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData th_large = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData help_circled = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData download_alt = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData export_icon = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData eye_1 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData cloud_upload = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData trending_up = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData print = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData calendar_1 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData picture_2 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData vcard = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData contacts = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData user_add = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData location_on = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData cogs = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData cog_1 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData folder_open = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData doc_text_1 = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData commerical_building = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData favorite = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture_1 = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData edit_1 = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData list_numbered = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData truck = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData phone_1 = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData down_open = const IconData(0xf004, fontFamily: _kFontFam);
  static const IconData up_open = const IconData(0xf005, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xf0b0, fontFamily: _kFontFam);
  static const IconData doc_text = const IconData(0xf0f6, fontFamily: _kFontFam);
  static const IconData star_half_alt = const IconData(0xf123, fontFamily: _kFontFam);
  static const IconData direction = const IconData(0xf124, fontFamily: _kFontFam);
  static const IconData rupee = const IconData(0xf156, fontFamily: _kFontFam);
  static const IconData sort_alt_down = const IconData(0xf161, fontFamily: _kFontFam);
  static const IconData building_filled = const IconData(0xf1ad, fontFamily: _kFontFam);
  static const IconData file_pdf = const IconData(0xf1c1, fontFamily: _kFontFam);
  static const IconData file_image = const IconData(0xf1c5, fontFamily: _kFontFam);
  static const IconData share_squared = const IconData(0xf1e1, fontFamily: _kFontFam);
  static const IconData calc = const IconData(0xf1ec, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
  static const IconData wpforms = const IconData(0xf298, fontFamily: _kFontFam);
}
